### ISSUE TITLE
TabLayout requires explicitly calling updateTemplate()

### ISSUE THREAD

**Issue by daniel-robertson** [microsoft/fluentui-android#292]
When inflating Fluent's TabLayout component via a Fragment's XML , it requires explicitly calling TabLayout.updateTemplate() to render correctly.

In an Activity or Adapter, the TabLayout component does not require explicitly calling this function, so I believe it is a bug.

See example before/after picture below:

Before calling updateTemplate() | After calling updateTemplate()
-|-
![Screenshot_20221129-164459_Yammer Dev](https://user-images.githubusercontent.com/949391/204681070-92002c1c-67bf-4f8e-ab94-8d73f4f66385.jpg)|![Screenshot_20221129-144639_Yammer Dev](https://user-images.githubusercontent.com/949391/204680546-9896c5c2-604a-4115-99ff-40ba04e21420.jpg)

**Comment by joyeeta26** [comment]
The need to explicitly call updateTemplate() in a Fragment's XML but not in an Activity or Adapter is likely due to the lifecycle differences between these components. Here are some potential reasons:  

**Fragment Lifecycle:** Fragments have a more complex lifecycle compared to Activities. The onAttachedToWindow() method, where updateTemplate() is called, might not be triggered at the same time or in the same way for Fragments as it is for Activities. This can result in the TabLayout not being fully initialized when the Fragment's view is created.  

**View Hierarchy:** When inflating views in a Fragment, the view hierarchy might not be fully established, causing certain methods like onAttachedToWindow() to not be called as expected. This can prevent updateTemplate() from being invoked automatically.  

**Delayed Initialization:** In Fragments, views might be initialized or attached to the window later than in Activities or Adapters. This delay can cause the TabLayout to miss the automatic call to updateTemplate().  

Closing this issue for now. Feel free to reopen if there are any further questions on this.
Thanks!
